platform :ios, '6.0'
pod 'UIView+FrameAdditions', '0.0.1'
pod 'FlurrySDK', '~>4.3'
pod 'BlocksKit', :git => 'https://github.com/pandamonia/BlocksKit.git', :branch => 'next'
pod 'UIImage+animatedGif', '~> 0.1.0'
